### ISSUE TITLE
Mod Request: Light Level Overlay Reloaded

### ISSUE THREAD

**Issue by matt-claycomb** [matt-claycomb/YellowsModpack-Config#2]
**Mod Details**
Light Level Overlay Reloaded

> This Minecraft mod visualizes the light levels emitted by torches, glowstone and alike directly on top of blocks, this is helpful to quickly identify areas where mobs can spawn. It shows the light level of the airblock above the block the number is drawn onto, this is the block that is considered for mob spawning, light level 7 or below allows mobs to spawn.

**Mod Link**
https://minecraft.curseforge.com/projects/light-level-overlay-reloaded

**Necessity**
This was a commonly used function of NEI which was not replicated in JEI. Currently no good way of visualizing when a block allows mob spawns.

**Comment by SybrenGL** [comment]
Will be added
